version: '3'
services:
  team_db:
      container_name: team_db
      image: mysql:debian
      env_file: env
      cap_add:
        - SYS_NICE
      command: ["--connect_timeout=28800", "--secure-file-priv="]
      volumes:
          - ./sql-scripts:/docker-entrypoint-initdb.d
          - db-data:/var/lib/mysql
          - ../dump_files:/dump_files
          - ./env:/env
      restart: unless-stopped
      networks:
        - app_network
      ports:
        - 3306:3306
        
volumes:
  db-data:
  
networks:
  app_network:
    driver: bridge
